import type { Metadata } from "next";

import "@/styles/main.scss";
import "@/styles/styles.scss";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Script
          src={`https://dapi.kakao.com/v2/maps/sdk.js?appkey=19371b70b65b8c001818d1dd5184e68a&autoload=false`}
          strategy="beforeInteractive"
        />
        {children}
      </body>
    </html>
  );
}
